// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyG0QrFSyTRgTrXYa7jWReXUmlzPlvX_w',
    appId: '1:630827413060:web:e186324148bd0b45975611',
    messagingSenderId: '630827413060',
    projectId: 'segno-a4dbc',
    authDomain: 'segno-a4dbc.firebaseapp.com',
    storageBucket: 'segno-a4dbc.appspot.com',
    measurementId: 'G-SKM83XQM9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdeJjz2RokgsIjbjm8zf-_eLxfzNMozfE',
    appId: '1:630827413060:android:495b4cad6dffd0a9975611',
    messagingSenderId: '630827413060',
    projectId: 'segno-a4dbc',
    storageBucket: 'segno-a4dbc.appspot.com',
  );
}
